### ISSUE TITLE
监测mysql的时候遇到一个报错

### ISSUE THREAD

**Issue by Akira-09** [Buzz2d0/MySQLMonitor#2]
closeLogRaw error: Error 1193: Unknown system variable 'log_raw'
Bye hacker :)
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.watchdog.func1(0xc0001fc2a0, 0xd2)
        /home/runner/work/MySQLMonitor/MySQLMonitor/MySQLMonitor.go:212 +0x65a
main.linePrinter(0xfb9840, 0xc00019a008, 0xf79860, 0x0, 0x0)
        /home/runner/work/MySQLMonitor/MySQLMonitor/MySQLMonitor.go:245 +0x271
main.watchdog()
        /home/runner/work/MySQLMonitor/MySQLMonitor/MySQLMonitor.go:226 +0x1b6
main.main()
        /home/runner/work/MySQLMonitor/MySQLMonitor/MySQLMonitor.go:98 +0x2e5

**Comment by Akira-09** [comment]
在my.ini上写死，永远开启日志还是会报这个错误，然后mysql的日志记录功能就会关闭

**Comment by Buzz2d0** [comment]
> 在my.ini上写死，永远开启日志还是会报这个错误，然后mysql的日志记录功能就会关闭

MySQL 什么版本

**Comment by ac0d3r** [comment]
> 在my.ini上写死，永远开启日志还是会报这个错误，然后mysql的日志记录功能就会关闭

MySQL 版本号多少？什么操作系统？
