### ISSUE TITLE
dial tcp 172.217.163.49:443: i/o timeout

### ISSUE THREAD

**Issue by xuanzhi201111** [Buzz2d0/MySQLMonitor#3]
go run MySQLMonitor.go -u root -p 123456
go: github.com/go-sql-driver/mysql@v1.6.0: Get "https://proxy.golang.org/github.com/go-sql-driver/mysql/@v/v1.6.0.mod": dial tcp 172.217.163.49:443: i/o timeout

**Comment by ac0d3r** [comment]
set proxy: https://goproxy.io
